# Generated by Django 4.2.27 on 2026-01-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='FISH')),
                ('region', models.CharField(choices=[('toshkent_sh', 'Toshkent shahri'), ('toshkent_vil', 'Toshkent viloyati'), ('andijon', 'Andijon viloyati'), ('buxoro', 'Buxoro viloyati'), ('fargona', "Farg'ona viloyati"), ('jizzax', 'Jizzax viloyati'), ('namangan', 'Namangan viloyati'), ('navoiy', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('samarqand', 'Samarqand viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('xorazm', 'Xorazm viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=50, verbose_name='Hudud')),
                ('credit_amount_range', models.CharField(choices=[('5000000', "5 000 000 so'm"), ('10000000', "10 000 000 so'm"), ('20000000', "20 000 000 so'm"), ('50000000', "50 000 000 so'm"), ('100000000', "100 000 000 so'm")], max_length=100, verbose_name='Kredit summasi')),
                ('collateral', models.CharField(choices=[('mashina', 'Mashina'), ('tilla', 'Tilla'), ('uy_joy', 'Uy-joy')], max_length=20, verbose_name='Garov')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
