# Generated by Django 4.2.27 on 2026-01-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='credit_amount_range',
        ),
        migrations.AddField(
            model_name='application',
            name='credit_amount',
            field=models.DecimalField(decimal_places=0, default=5000000, max_digits=12, verbose_name='Kredit summasi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='collateral',
            field=models.CharField(choices=[('mashina', 'Avtomobil (Tezkor)'), ('tilla', 'Tilla buyumlar (Ishonchli)'), ('uy_joy', "Ko'chmas mulk (Katta summa)")], max_length=20, verbose_name='Garov'),
        ),
    ]
