# Generated by Django 4.2.27 on 2026-01-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_application_credit_amount_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default=998901234567, max_length=13, verbose_name='Telefon raqam'),
            preserve_default=False,
        ),
    ]
