# Generated by Django 4.2.27 on 2026-01-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('website', 'Veb-sayt'), ('telegram', 'Telegram Bot')], default='website', max_length=20, verbose_name='Manba'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
    ]
